project_id = "upzhhgrozngmsorhrbch"

[functions.setup-admin]
verify_jwt = false

[functions.wave-payment]
verify_jwt = false

[functions.seed-zones]
verify_jwt = false

[functions.create-user]
verify_jwt = false
