// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upzhhgrozngmsorhrbch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwemhoZ3Jvem5nbXNvcmhyYmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTI1ODEsImV4cCI6MjA4Nzc4ODU4MX0.PSwBy2uGRnVxvx6AeopdIq2wVm-iE3M6hnvrTCIKLeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});